config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins
  #devise_for :customers

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  	sessions: 'admins/sessions',
  	passwords: 'admins/passwords',
  	registrations: 'admins/registrations'
  }
  devise_for :customers, skip: [:passwords], controllers: {
  	sessions: 'customers/sessions',
  	passwords: 'customers/passwords',
  	registrations: 'customers/registrations'
  }
  # 顧客側
  # homesコントローラー
  root 'homes#top'
  get 'about' => 'homes#about'
  # customersコントローラ-
  get '/customer/confirm_unsubscribing' => 'customers#confirm_unsubscribing'
  get 'customer/:id' => 'customers#show'

  # shipping_addressesコントローラ
  resources :shipping_addresses, only: [:index, :edit, :update, :destroy, :create]
  #productsコントローラ
  resources :products, only: [:index, :show]
  # cart_itemsコントローラ
  resources :cart_items, only: [:index, :create, :destroy, :update]
  delete 'cart_items' => 'cart_items#items_destroy'
  # ordersコントローラ
  post 'orders/cofirm' => 'orders#confirm'
  get 'orders/thanks' => 'orders#thanks'
  resources :orders, only: [:index, :show, :new, :create]
  # 管理側
  namespace :admin do
	  # admin/admins(devise)コントローラ
    get '/' => 'homes#top'
    # admin/search コントローラ
    post 'search_result' => 'search#search_result'
    get 'search_result' => 'homes#top'
	  # admin/productsコントローラ
	  resources :products, only: [:index, :new, :show, :edit, :create, :update]
	  # admin/categoriesコントローラ
	  resources :categories, only: [:index, :edit, :create, :update]
	  # admin/customersコントローラ
	  resources :customers, only: [:index, :show, :edit, :update]
	  # admin/ordersコントローラ
	  resources :orders, only: [:index, :show, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shipping_addresses
  has_many :cart_items
  has_many :orders

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :address, presence: true
  validates :postcode, presence: true, length: { minimum: 7 }, numericality: { only_integer: true }
  validates :phone_number, presence: true, length: { minimum: 9 }, numericality: { only_integer: true }
  validates :postcode, presence: true
  validates :phone_number, presence: true

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

    before_action :authenticate_admin!

    def index
        @customers = Customer.page(params[:page])
	end

	def show
		@customer =  Customer.find(params[:id])
    end

    def edit
    	@customer =  Customer.find(params[:id])
    end

    def update
    	@customer = Customer.find(params[:id])
        if @customer.update(customer_params)
            flash[:notice] = "顧客情報を編集しました"
           redirect_to(admin_customer_path(@customer))
        else
            @customer =  Customer.find(params[:id])
            render(:edit)
        end
    end

    private
    def customer_params
        params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postcode, :address, :phone_number, :email, :is_active)
    end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource

  def update
    if params[:unsubscribing] == "true"
      customer = current_customer
      customer.update(is_active: false)
      sign_out
      flash[:notice] = "退会済みです"
      redirect_to root_path
      return
    end

    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      set_flash_message_for_update(resource, prev_unconfirmed_email)
      bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?

      respond_with resource, location: after_update_path_for(resource)
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end


  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_action :authenticate_customer!
  before_action :ensure_correct_customer, only: [:show]

  def show
  	@customer = Customer.find(params[:id])
  end

  def confirm_unsubscribing
  	@customer = current_customer
  end

  private
  def customer_params
    params.require(:customer).permit(:first_name,:last_name,:first_name_kana,:last_name_cana, :postcode, :address,:phone_number,:email)
  end

  # 他のcustomer がアクセスできないようにする
  def ensure_correct_customer
    customer = Customer.find(params[:id])
    if customer != current_customer
        flash[:notice] = "権限がありません"
        redirect_to("/customers/#{current_customer.id}")
    end
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/edit.html.erb
<h3> 会員編集画面 </h3>

<% if @customer.errors.any? %>
　  <div id="error_explanation">
      <h4>【 入力されていない項目があります。 】</h4>
  　</div>
<% end %>

<div class="customer_edit">

  <div class="customer_edit_field">
    <span class="customer_edit_title">会員ID</span>
    <span class="customer_edit_content"><%= @customer.id %></span>
  </div>

  <%= form_with(model: @customer, url: admin_customer_path(@customer.id), method: :PATCH, local: true) do |f| %>

    <div class="customer_edit_field">
      <span class="customer_edit_title">氏名</span>
      <span class="customer_edit_content"><%= f.text_field(:first_name) %><%= f.text_field (:last_name) %></span>
    </div>


    <div class="customer_edit_field">
      <span class="customer_edit_title">フリガナ</span>
      <span class="customer_edit_content"><%= f.text_field(:first_name_kana) %><%= f.text_field(:last_name_kana) %></span>
    </div>


    <div class="customer_edit_field">
      <span class="customer_edit_title">郵便番号</span>
      <span class="customer_edit_content"><%= f.text_field(:postcode) %></span>
    </div>


    <div class="customer_edit_field">
	   <span class="customer_edit_title">住所</span>
	   <span class="customer_edit_content"><%= f.text_field(:address) %></span>
    </div>


    <div class="customer_edit_field">
	   <span class="customer_edit_title">電話番号</span>
	   <span class="customer_edit_content"><%= f.telephone_field(:phone_number) %></span>
    </div>


    <div class="customer_edit_field">
	   <span class="customer_edit_title">メールアドレス</span>
	   <span class="customer_edit_content"><%= f.email_field(:email) %></span>
    </div>


    <div class="customer_edit_field">
      <span class="customer_edit_title">会員ステータス</span>
      <span class="customer_edit_content">
	      <label><%=f.radio_button(:is_active, true) %>有効</label>
	      <label><%=f.radio_button(:is_active, false) %>退会済み</label>
      </span>
    </div>


    <div class="customer_edit_action">
      <%= f.submit("変更を保存する", class: "btn btn-primary") %>
    </div>

  <% end %>

</div>

<style>
  h3{ margin-bottom: 40px; }
  .customer_edit_field { margin-bottom: 20px; }
  .customer_edit_title { display: inline-block; width: 150px; }
  .customer_edit_action { position: relative; top: 20px;}

app/views/admin/customers/index.html.erb
<h3> 会員一覧画面 </h3>

<table class="table table-hover table-inverse">
    <thead>
    	<tr class="active">
      　　<th>会員ID</th>
      　　<th>氏名</th>
      　　<th>メールアドレス</th>
      　　<th>ステータス</th>
      </tr>
    </thead>

    <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td>
              <%= customer.id %>
            </td>
            <td>
              <%= link_to(customer.first_name + customer.last_name, admin_customer_path(customer)) %>
            </td>
            <td>
              <%= customer.email %>
            </td>
            <td>
              <% if customer.is_active == true %>
                有効
              <% else %>
                退会済
              <% end %>
            </td>
          </tr>
        <% end %>
    </tbody>
</table>

<div class="row">
  <div class="col-md-4 col-md-offset-6">
    <%= paginate @customers, class: "paginate" %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<h3> 会員詳細画面 </h3>

<h5>
  <span class="customer_title">顧客ID</span>
  <span class="customer_content">
    <span class="customer_id"><%= @customer.id %>
    <span class="customer_status">
      <% if @customer.is_active == true %>
        有効会員
      <% else %>
        無効会員
      <% end %>
    </span>
  </span>
</h5>

<h5>
  <span class="customer_title">氏名</span>
  <span class="customer_content"><%= @customer.first_name + @customer.last_name %></span>
</h5>


<h5>
  <span class="customer_title">フリガナ</span>
  <span class="customer_content"><%= @customer.first_name_kana + @customer.last_name_kana %></span>
</h5>


<h5>
  <span class="customer_title">郵便番号</span>
  <span class="customer_content"><%= @customer.postcode %></span>
</h5>


<h5>
  <span class="customer_title">住所</span>
  <span class="customer_content"><%= @customer.address %></span>
</h5>


<h5>
  <span class="customer_title">電話番号</span>
  <span class="customer_content"><%= @customer.phone_number %></span>
</h5>


<h5>
  <span class="customer_title">メールアドレス</span>
  <span class="customer_content"><%= @customer.email %></span>
</h5>


<div class="action">
  <%= link_to("編集する", edit_admin_customer_path(@customer), class:'btn btn-primary') %>
  <%= link_to("注文履歴一覧を見る", admin_orders_path, class:'btn btn-primary') %>
</div>


<style>
  h3{ margin-bottom: 40px; }
  h5 { margin-bottom: 30px; }
  .customer_title { display: inline-block; width: 150px; }
  .customer_content { display: inline-block; width: 200px; }
  .customer_status { border: 1px solid black; background-color: #87CEFA; padding: 2px; margin-left: 10px; border-radius:5px; }
  .action { position: relative; top: 50px;}
</style>