config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins
  #devise_for :customers

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  	sessions: 'admins/sessions',
  	passwords: 'admins/passwords',
  	registrations: 'admins/registrations'
  }
  devise_for :customers, skip: [:passwords], controllers: {
  	sessions: 'customers/sessions',
  	passwords: 'customers/passwords',
  	registrations: 'customers/registrations'
  }
  # 顧客側
  # homesコントローラー
  root 'homes#top'
  get 'about' => 'homes#about'
  # customersコントローラ-
  get '/customer/confirm_unsubscribing' => 'customers#confirm_unsubscribing'
  get 'customer/:id' => 'customers#show'

  # shipping_addressesコントローラ
  resources :shipping_addresses, only: [:index, :edit, :update, :destroy, :create]
  #productsコントローラ
  resources :products, only: [:index, :show]
  # cart_itemsコントローラ
  resources :cart_items, only: [:index, :create, :destroy, :update]
  delete 'cart_items' => 'cart_items#items_destroy'
  # ordersコントローラ
  post 'orders/cofirm' => 'orders#confirm'
  get 'orders/thanks' => 'orders#thanks'
  resources :orders, only: [:index, :show, :new, :create]
  # 管理側
  namespace :admin do
	  # admin/admins(devise)コントローラ
    get '/' => 'homes#top'
    # admin/search コントローラ
    post 'search_result' => 'search#search_result'
    get 'search_result' => 'homes#top'
	  # admin/productsコントローラ
	  resources :products, only: [:index, :new, :show, :edit, :create, :update]
	  # admin/categoriesコントローラ
	  resources :categories, only: [:index, :edit, :create, :update]
	  # admin/customersコントローラ
	  resources :customers, only: [:index, :show, :edit, :update]
	  # admin/ordersコントローラ
	  resources :orders, only: [:index, :show, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :customer
	belongs_to :product

	validates :amount, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

    before_action :authenticate_customer!
    before_action :ensure_correct_customer, only: [:destroy, :update]

    def index
        @cart_items = CartItem.where(customer_id: current_customer.id)
    end

    def create
        cart_item = CartItem.find_by(product_id: params[:cart_item][:product_id], customer_id: current_customer.id)
        # カート内に同じ商品がある場合、数量を追加する
        if cart_item.present?
            cart_item.amount += params[:cart_item][:amount].to_i
            cart_item.save
        else
            cart_item = CartItem.new(cart_item_params)
            cart_item.customer_id = current_customer.id
            if cart_item.valid?
                cart_item.save
                flash[:notice] = "カートに追加しました"
            else
                flash[:notice] = "数値が不正です"
                @product = Product.find(params[:cart_item][:product_id])
                @cart_item = CartItem.new
                @categories=Category.all
                render("products/show")
            end
        end
        redirect_to(cart_items_path)
    end

    # 特定のcart_item一件を削除する
    def destroy
        cart_item = CartItem.find(params[:id])
        cart_item.destroy
        @cart_items = CartItem.where(customer_id: current_customer.id)
    end

    def update
        cart_item = CartItem.find(params[:id])
        cart_item.update(amount: params[:cart_item][:amount])
        @cart_items = CartItem.where(customer_id: current_customer.id)
    end

    # current_customerに紐付く、cart_itemsを取得し、全件削除する。
    def items_destroy
        @cart_items = CartItem.where(customer_id: current_customer.id)
        @cart_items.destroy_all
    end

    private
    def cart_item_params
        params.require(:cart_item).permit(:product_id, :amount)
    end

    # 他のcustomer がアクセスできないようにする
    def ensure_correct_customer
        cart_item = CartItem.find(params[:id])
        if cart_item.customer != current_customer
            flash[:notice] = "権限がありません"
            redirect_to("/customers/#{current_customer.id}")
        end
    end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/_index.html.erb
<div class="col-md-12">
        <table class="table table-hover table-inverse table-bordered">
            <thead>
                <tr class="active">
                    <th>商品名</th>
                    <th>単価（税込）</th>
                    <th>数量</th>
                    <th>小計</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <%# カート内の商品全ての合計金額を計算する %>
                <% total_price = 0%>
                <% cart_items.each do |cart_item| %>
                    <tr>
                        <td>
                            <%= link_to(product_path(cart_item.product_id)) do %>
                                <%= attachment_image_tag(cart_item.product, :product_image, :fill, 30, 30) %>
                                <%= cart_item.product.name %>
                            <% end %>
                        </td>
                        <td>
                            <span><%= (cart_item.product.price * (1 + $tax_rate)).round %></span>
                        </td>
                        <td>
                            <div class="amount">
                                <%= form_with(model: cart_item, url: cart_item_path(cart_item.id), data: {remote: true}, method: :PATCH) do |f| %>
                                    <%= f.number_field(:amount, min: 1) %>
                                    <%= f.hidden_field(:product_id, value: cart_item.id) %>
                                    <%= f.submit('変更', class: "btn btn-primary btn-sm") %>
                                <% end %>
                            </div>
                        </td>
                        <td>
                            <%# 商品ごとの小計を計算 %>
                            <% sub_total = (cart_item.product.price * (1 + $tax_rate)).round * cart_item.amount %>
                            <span><%= sub_total %></span>
                            <% total_price += sub_total %>
                        </td>
                        <td>
                            <div class="delete">
                                <%= link_to("削除する", cart_item_path(cart_item.id), remote:true, method: :DELETE, class: "btn btn-danger btn-sm") %>
                            </div>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>

    <div class="row">
        <div class="col-md-2">
        <%= link_to("買い物を続ける", products_path, class: "btn btn-primary") %>
        </div>
        <div class="col-md-3 col-md-offset-7">
        <table class="table table-bordered">
            <tr>
                <th class="active total_price">合計金額</th>
                <td><%= total_price %></td>
            </tr>
        </table>
    </div>
    <div id="link">
        <%= link_to("情報入力に進む", new_order_path, class: "btn btn-primary") %>
    </div>
</div>

app/views/cart_items/destroy.js.erb
$("#cart_items_index").html("<%= j(render 'index',  cart_items: @cart_items) %>")

app/views/cart_items/index.html.erb
<div class= "row">
    <div class="col-md-10">
        <h3>ショッピングカート</h3>
    </div>
    <div class="col-md-2 delete_cart">
        <%= link_to("カートを空にする", "/cart_items", remote:true, method: :DELETE, class: "btn btn-danger") %>
    </div>
</div>

<div id="cart_items_index">
    <%= render('index', cart_items: @cart_items) %>
</div>

<style>
.delete_cart{ margin-top: 20px; }
.active{ font-family: sans-serif; }
#link{ text-align: center; }
#link .btn-primary{
    padding-top: 18px;
    width: 300px;
    height: 60px;
}
td .delete{ text-align: center; }
td .amount{ text-align: center; }
span{ display:block; margin-top: 7px; }
input[type="number"] {
        width: 40px;
        height: 30px;
}
</style>

app/views/cart_items/items_destroy.js.erb
$("#cart_items_index").html("<%= j(render 'index',  cart_items: @cart_items) %>")

app/views/cart_items/update.js.erb
$("#cart_items_index").html("<%= j(render 'index',  cart_items: @cart_items) %>")