config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins
  #devise_for :customers

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  	sessions: 'admins/sessions',
  	passwords: 'admins/passwords',
  	registrations: 'admins/registrations'
  }
  devise_for :customers, skip: [:passwords], controllers: {
  	sessions: 'customers/sessions',
  	passwords: 'customers/passwords',
  	registrations: 'customers/registrations'
  }
  # 顧客側
  # homesコントローラー
  root 'homes#top'
  get 'about' => 'homes#about'
  # customersコントローラ-
  get '/customer/confirm_unsubscribing' => 'customers#confirm_unsubscribing'
  get 'customer/:id' => 'customers#show'

  # shipping_addressesコントローラ
  resources :shipping_addresses, only: [:index, :edit, :update, :destroy, :create]
  #productsコントローラ
  resources :products, only: [:index, :show]
  # cart_itemsコントローラ
  resources :cart_items, only: [:index, :create, :destroy, :update]
  delete 'cart_items' => 'cart_items#items_destroy'
  # ordersコントローラ
  post 'orders/cofirm' => 'orders#confirm'
  get 'orders/thanks' => 'orders#thanks'
  resources :orders, only: [:index, :show, :new, :create]
  # 管理側
  namespace :admin do
	  # admin/admins(devise)コントローラ
    get '/' => 'homes#top'
    # admin/search コントローラ
    post 'search_result' => 'search#search_result'
    get 'search_result' => 'homes#top'
	  # admin/productsコントローラ
	  resources :products, only: [:index, :new, :show, :edit, :create, :update]
	  # admin/categoriesコントローラ
	  resources :categories, only: [:index, :edit, :create, :update]
	  # admin/customersコントローラ
	  resources :customers, only: [:index, :show, :edit, :update]
	  # admin/ordersコントローラ
	  resources :orders, only: [:index, :show, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :cart_items
	has_many :ordered_items
	belongs_to :category

	attachment :product_image

	validates :name, presence: true
	validates :content, presence: true
	validates :price, presence: true
	validates :product_image, presence: true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

    before_action :authenticate_admin!

	def index
        @products = Product.order(created_at: :asc).page(params[:page])
    end

    def new
        @product = Product.new
        @active_category = Category.where(is_active: true)
    end

    def show
        @product = Product.find(params[:id])
    end

    def create
        @product = Product.new(product_params)
        if @product.save
            flash[:notice] = "商品を登録しました。"
            redirect_to(admin_product_path(@product))
        else
            @product = Product.new
            @active_category = Category.where(is_active: true)
            render(:new)
        end
    end

    def edit
        @product = Product.find(params[:id])
        @active_category = Category.where(is_active: true)
    end

    def update
        @product = Product.find(params[:id])
        if @product.update(product_params)
            flash[:notice] = "商品を編集しました。"
           redirect_to admin_product_path(@product)
        else
            @product = Product.find(params[:id])
            @active_category = Category.where(is_active: true)
            render(:edit)
        end
    end


    private
    def product_params
          params.require(:product).permit(:name, :content, :category_id, :price, :is_active, :product_image)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @categories = Category.all
    if params[:category_id].present?
      # params[:category_id]が存在する場合、ジャンルに紐付く商品のみ取得する
      @category = Category.find(params[:category_id].to_i)
      @products = Product.where(category_id: @category.id).order(created_at: :DESC).page(params[:page]).per(6)
    else
      # params[:category_id]が存在しない場合、商品を全て取得する
      @products = Product.order(created_at: :DESC).page(params[:page]).per(6)
    end
  end

  def show
    @categories = Category.all
    @product = Product.find(params[:id])
    @cart_item = CartItem.new
  end

  private
    def product_params
      params.require(:product).permit(:name, :content, :price, :product_image, :is_active)
    end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<h3> 商品 編集画面 </h3>

<% if @product.errors.any? %>
    <div id="error_explanation">
        <h4>【 入力されていない項目があります。 】</h4>
  　</div>
<% end %>

<div class="row">

  <%= form_with(model: @product, url: admin_product_path(@product.id), local: true, method: :PATCH) do |f| %>

    <div class="col-sm-4">
      <%= attachment_image_tag(@product, :product_image, :fill, 250, 200, format: 'jpeg') %>
      <%= f.attachment_field(:product_image) %>
    </div>

    <div class="col-sm-5">

      <div class="product_edit_field">
        <span class="edit_title">商品名</span>
        <span class="edit_content"><%= f.text_field(:name) %></span>
      </div>


      <div class="product_edit_field">
        <span class="edit_title">商品説明</span>
        <span class="edit_content"><%= f.text_area(:content) %></span>
      </div>


      <div class="product_edit_field">
        <span class="edit_title">ジャンル</span>
        <span class="edit_content">
          <%= f.collection_select(:category_id, @active_category, :id, :name)%>
        </span>
      </div>


      <div class="product_edit_field">
        <span class="edit_title">税抜価格</span>
        <span class="edit_content"><%= f.text_field(:price) %> 円</span>
      </div>


      <div class="product_edit_field">
        <span class="edit_title">販売ステータス</span>
        <span class="edit_content">
          <%= f.select(:is_active, [["販売中", true],["売り切れ", false]] , include_blank: "選択して下さい") %>
        </span>
      </div>


      <div class="col-sm-3">
        <div class="product_edit_action">
          <%= f.submit("変更を保存", class: "btn btn-primary") %>
        </div>
      </div>

    </div>

  <% end %>

</div>

<style>
  h3 {  margin: 0 0 0 10px ; }
  .row  { margin: 45px 0 0 30px ; }
  input[type="file"] { display: block; font-size: 15px; margin-top: 50px; }
  .product_edit_field { margin: 0 0 20px; font-size: 15px; }
  .edit_title {display: inline-block; width: 150px; }
  .edit_content {display: inline-block; width: 200px;}
  .btn-primary { position: relative; top: 250px; left: 120px ;}
</style>

app/views/admin/products/index.html.erb
<h3>
   商品一覧画面
   <span>
     <%= link_to("", new_admin_product_path, class: 'glyphicon glyphicon-plus-sign') %>
   </span>
</h3>

<table class="table table-hover table-inverse">
    <thead>
      <tr class="active">
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
          <th></th>
        </tr>
    </thead>

    <tbody>
        <% @products.each do |product| %>
          <tr>
            <td>
              <%= product.id %>
            </td>
            <td>
              <%= link_to(product.name, admin_product_path(product.id)) %>
            </td>
            <td>
              <%= product.price %>
            </td>
            <td>
              <%= product.category.name %>
            </td>
            <td>
              <% if product.is_active == true %>
                販売中
              <% else %>
                販売停止中
              <% end %>
            </td>
          </tr>
        <% end %>
    </tbody>
</table>

<%= paginate @products, class: "paginate" %>

<style>
  .glyphicon-plus-sign:before { margin: 0 0 0 790px; color: #CC9966;}
</style>

app/views/admin/products/new.html.erb
<h3> 商品　新規登録画面 </h3>

<% if @product.errors.any? %>
　  <div id="error_explanation">
      <h4>【 入力されていない項目があります。 】</h4>
  　</div>
<% end %>

<div class="row">

  <%= form_with(model: @product, url: admin_products_path, local: true) do |f| %>

    <%# アップロードした画像をプレビューする %>
    <div class="col-sm-3">
      <div class="view_box">
        <label for="product_product_image" class="file_field btn">
          ファイルを選択
          <%= f.attachment_field(:product_image, type: 'file', class:'file') %>
        </label>
      </div>
    </div>

    <div class="col-sm-5">

      <div class="product_new_field">
        <span class="new_title">商品名</span>
        <span class="new_content"><%= f.text_field(:name) %></span>
      </div>


      <div class="product_new_field">
        <span class="new_title">商品説明</span>
        <span class="new_content"><%= f.text_area(:content) %></span>
      </div>


      <div class="product_new_field"><!-- ジャンル名を表示させるためにカテゴリーモデルからデータをひっぱってくる　-->
        <span class="new_title">ジャンル</span>
        <span class="new_content"><%= f.collection_select(:category_id, @active_category, :id, :name, include_blank: "選択して下さい" )%></span>
      </div>


      <div class="product_new_field">
        <span class="new_title">税抜価格</span>
        <span class="new_content"><%= f.text_field(:price) %> 円 </span>
      </div>


      <div class="product_new_field">
        <span class="new_title">販売ステータス</span>
        <span class="new_content">
          <%= f.select(:is_active, [["販売中", true],["売り切れ", false]] , include_blank: "選択して下さい") %>
        </span>
      </div>
    </div>


    <div class="col-sm-4">
      <div class="product_new_action">
        <%= f.submit("新規登録", class: "btn btn-primary") %>
      </div>
    </div>

  <% end %>

</div>

<style>
  .col-sm-5 { position: relative; top: 40px; }
  .file_field input { display: none;}
  .file_field{ background: #337ab7; color: #FFFFFF; display: inline-block; margin : 0px 0 10px 0; }
  h3 {  margin: 0 0 0 10px ; }
  .row { margin: 45px 0 0 30px ; }
  .view_box { display: block; font-size: 15px; position: relative; right: 50px; }
  .product_new_field { margin: 0 0 20px; font-size: 15px; }
  .new_title {display: inline-block; width: 150px; }
  .new_content {display: inline-block; width: 200px;}
  .btn-primary { position: relative; top: 250px; left: 120px ;}
</style>

app/views/admin/products/show.html.erb
<h3> 商品　詳細画面 </h3>

<div class="row">

    <div class="col-sm-4">
        <div class="admin_product_show_image">
            <%= attachment_image_tag(@product, :product_image, :fill, 250, 200, format: 'jpeg') %>
        </div>
    </div>

    <div class="col-sm-5">

        <h5>
            <span class="title">商品名</span>
            <span class="content"><%= @product.name %></span>
        </h5>

        <h5>
            <span class="title">商品説明</span>
            <span class="content"><%= @product.content %></span>
        </h5>

        <h5>
            <span class="title">ジャンル</span>
            <span class="content"><%= @product.category.name %></span>
        </h5>

        <h5>
            <span class="title">税込価格（税抜価格）</span>
            <span class="content"><%= (@product.price * (1 + $tax_rate)).round %> &nbsp; ( <%= @product.price %> )&nbsp;円</span>
        </h5>

        <h5>
            <span class="title">販売ステータス</span>
            <span class="content">
                <% if @product.is_active == true %>
                    販売中
                <% else %>
                    売り切れ
                <% end %>
            </span>
        </h5>

    </div>

    <div class="col-sm-3">
        <%= link_to("編集する", edit_admin_product_path(@product), class:'btn btn-primary') %>
    </div>

</div>

<style>
    h3  { margin: 0 0 0 10px ; }
    .row { margin: 45px 0 0 30px ; }
    h5 { margin: 0 0 28px; font-size: 15px; }
    .title {display: inline-block; width: 200px; }
    .content {display: inline-block; width: 200px;}
    .btn-primary { position: relative; top: 250px; left: 120px ;}
</style>