config/routes.rb
Rails.application.routes.draw do
  #devise_for :admins
  #devise_for :customers

  devise_for :admins, skip: [:registrations, :passwords], controllers: {
  	sessions: 'admins/sessions',
  	passwords: 'admins/passwords',
  	registrations: 'admins/registrations'
  }
  devise_for :customers, skip: [:passwords], controllers: {
  	sessions: 'customers/sessions',
  	passwords: 'customers/passwords',
  	registrations: 'customers/registrations'
  }
  # 顧客側
  # homesコントローラー
  root 'homes#top'
  get 'about' => 'homes#about'
  # customersコントローラ-
  get '/customer/confirm_unsubscribing' => 'customers#confirm_unsubscribing'
  get 'customer/:id' => 'customers#show'

  # shipping_addressesコントローラ
  resources :shipping_addresses, only: [:index, :edit, :update, :destroy, :create]
  #productsコントローラ
  resources :products, only: [:index, :show]
  # cart_itemsコントローラ
  resources :cart_items, only: [:index, :create, :destroy, :update]
  delete 'cart_items' => 'cart_items#items_destroy'
  # ordersコントローラ
  post 'orders/cofirm' => 'orders#confirm'
  get 'orders/thanks' => 'orders#thanks'
  resources :orders, only: [:index, :show, :new, :create]
  # 管理側
  namespace :admin do
	  # admin/admins(devise)コントローラ
    get '/' => 'homes#top'
    # admin/search コントローラ
    post 'search_result' => 'search#search_result'
    get 'search_result' => 'homes#top'
	  # admin/productsコントローラ
	  resources :products, only: [:index, :new, :show, :edit, :create, :update]
	  # admin/categoriesコントローラ
	  resources :categories, only: [:index, :edit, :create, :update]
	  # admin/customersコントローラ
	  resources :customers, only: [:index, :show, :edit, :update]
	  # admin/ordersコントローラ
	  resources :orders, only: [:index, :show, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :cart_items
	has_many :ordered_items
	belongs_to :category

	attachment :product_image

	validates :name, presence: true
	validates :content, presence: true
	validates :price, presence: true
	validates :product_image, presence: true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

    before_action :authenticate_admin!

	def index
        @products = Product.order(created_at: :asc).page(params[:page])
    end

    def new
        @product = Product.new
        @active_category = Category.where(is_active: true)
    end

    def show
        @product = Product.find(params[:id])
    end

    def create
        @product = Product.new(product_params)
        if @product.save
            flash[:notice] = "商品を登録しました。"
            redirect_to(admin_product_path(@product))
        else
            @product = Product.new
            @active_category = Category.where(is_active: true)
            render(:new)
        end
    end

    def edit
        @product = Product.find(params[:id])
        @active_category = Category.where(is_active: true)
    end

    def update
        @product = Product.find(params[:id])
        if @product.update(product_params)
            flash[:notice] = "商品を編集しました。"
           redirect_to admin_product_path(@product)
        else
            @product = Product.find(params[:id])
            @active_category = Category.where(is_active: true)
            render(:edit)
        end
    end


    private
    def product_params
          params.require(:product).permit(:name, :content, :category_id, :price, :is_active, :product_image)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @categories = Category.all
    if params[:category_id].present?
      # params[:category_id]が存在する場合、ジャンルに紐付く商品のみ取得する
      @category = Category.find(params[:category_id].to_i)
      @products = Product.where(category_id: @category.id).order(created_at: :DESC).page(params[:page]).per(6)
    else
      # params[:category_id]が存在しない場合、商品を全て取得する
      @products = Product.order(created_at: :DESC).page(params[:page]).per(6)
    end
  end

  def show
    @categories = Category.all
    @product = Product.find(params[:id])
    @cart_item = CartItem.new
  end

  private
    def product_params
      params.require(:product).permit(:name, :content, :price, :product_image, :is_active)
    end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_category_form.html.erb
<div class="col-xs-3">
    <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">ジャンル検索</h3>
        </div>
        <div class="panel-body">
          <ul type="square">
            <% categories.each do |category| %>
              <li><%= link_to("#{category.name}", products_path(category_id: category.id)) %></li>
            <% end %>
          </ul>
        </div>
    </div>
</div>

<style>
    .panel {
        min-height: 200px
    }
</style>

app/views/products/index.html.erb
 <div class="row">
  <%= render('category_form', categories: @categories) %>
  <div class="col-xs-9">
    <h3>
      <% if @category.blank? %>
        商品一覧
      <% else %>
        <%= @category.name %>一覧
      <% end %>
      <% if @products.blank? %>
        /<span style="color: red;">商品がありません</span>
      <% end %>
    </h3>

    <div class="row">
      <% @products.each do |product| %>
        <div class="col-xs-4 product-container">
          <ul class="product-list">
            <li><%= attachment_image_tag(product, :product_image, size:"200x150", format: 'jpeg') %></li>
            <li><%= link_to(product.name, product_path(product.id)) %></li>
            <li><%= "¥" + (product.price * (1 + $tax_rate)).round.to_s %></li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>

  <div>
  <div class="row">
    <div class="col-md-4 col-md-offset-6">
      <%= paginate @products %>
    </div>
  </div>
</div>

<style>
  .product-list {
    list-style: none;
  }
  .product-list li {
    margin-top: 15px;
  }
</style>

app/views/products/show.html.erb
<div class="row">
  <%= render('category_form', categories: @categories) %>
  <div class="col-xs-4">
    <%= attachment_image_tag(@product, :product_image, size:  "350x300", format: 'jpeg') %>
  </div>
  <div class="col-xs-5">
    <div class="panel panel-warning">
      <div class="panel-heading">
        <div class="panel-title">
          <%= @product.name %>
        </div>
      </div>
      <div class="panel-body">
        <h4>商品説明</h4>
        <p><%= @product.content %></p>
        <h4>価格</h4>
        <p><span class="price">￥<%= (@product.price * (1 + $tax_rate)).round.to_s %></span>（税込）</p>
        <p>ただいま、<%= CartItem.where(product_id: @product.id).count %>人がカートに入れています。</p>
      </div>
    </div>
    <%= form_with(model: @cart_item, url: cart_items_path, local: true) do |f| %>
      <%= f.number_field(:amount, min: 1) %>
      <%= f.hidden_field(:product_id, value: @product.id) %>
      <%= f.submit('カートに入れる',class: "btn btn-primary") %>
    <% end %>
  </div>
</div>
<style>
  .price {
    font-size: 20px;
    font-weight: bold;
  }
</style>